describe('Register', () => {
    it('Registers a user', () => {
        cy.visit('http://localhost:3000/register')
        cy.contains('Welcome to React Router!')
        cy.get('[href="/Blog"]')
        .should('be.visible')
        cy.get('[href="/CreatePost"]')
        .should('be.visible')
        cy.get('[href="/cars"]')
        .should('be.visible')
        cy.get('[type="email"]')
        .should('be.visible')
        .type('abc@gmail.com')
        cy.get('[type="password"]')
        .should('be.visible')
        .type('abc')
        cy.get('[type="name"]')
        .should('be.visible')
        .type('abc')
        cy.get('button')
        .should('be.visible')
    })
  })